theme: jekyll-theme-hacker
title: Hoff's Home
description: Ramblings, musings, collection of crap from other places, perhaps.
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
site:
  show_downloads: false
  show_github_url: false
  
